export const routes = [
    { path: '/', name: 'Главная' },
    { path: '/home', name: 'Главная' },
    { path: '/recommendations', name: 'Рекомендации' },
    { path: '/recommendations/tops', name: 'Топы' },
    { path: '/recommendations/collections', name: 'Подборки' },
    { path: '/catalog', name: 'Каталог' },
    { path: '/favorites', name: 'Избранное' },
    { path: '/account/reader', name: 'Читатель' },
    { path: '/account/reader/bookhistory', name: 'История книг' },
    { path: '/account/reader/reviewhistory', name: 'История отзывов' },
    { path: '/account/librarian', name: 'Библиотекарь' },
    { path: '/account/librarian/books', name: 'Книги' },
    { path: '/account/librarian/readers', name: 'Читатели' },
    { path: '/account/librarian/reviews', name: 'Отзывы' },
    { path: '/authorisation', name: 'Авторизация' },
    { path: '/authorisation/forget_password', name: 'Забыли пароль' },
    { path: '/registration', name: 'Регистрация' },
]